import { z } from 'zod';
import { prisma } from '../config/prisma';
import { failure, success } from '../utils/response';
import type { Request, Response } from 'express';
import { allowRoles } from '../middleware/auth';

export const idSchema = z.object({ id: z.string().min(1) });
const memberInput = z.object({ name: z.string().min(2), phone: z.string().min(7), email: z.string().email().optional(), password: z.string().min(8).default('ChangeMe123!'), fitnessGoal: z.string().optional(), heightCm: z.number().positive().optional(), weightKg: z.number().positive().optional() });

export async function listMembers(req: Request, res: Response) { const members = await prisma.member.findMany({ where: req.auth!.role === 'TRAINER' ? { assignedTrainers: { some: { trainer: { userId: req.auth!.sub } } } } : { isActive: true }, include: { user: { select: { id: true, name: true, phone: true, email: true, status: true } }, subscriptions: { where: { isDeleted: false }, orderBy: { endDate: 'desc' }, take: 1 } } }); return success(res, members); }
export async function getMember(req: Request, res: Response) { const { id } = idSchema.parse(req.params); const member = await prisma.member.findUnique({ where: { id }, include: { user: { select: { id: true, name: true, phone: true, email: true, status: true } }, subscriptions: { include: { plan: true, service: true }, orderBy: { endDate: 'desc' } }, payments: { orderBy: { createdAt: 'desc' } }, attendance: { orderBy: { checkInTime: 'desc' }, take: 30 }, progress: { orderBy: { measuredAt: 'desc' } }, ptSessions: true } }); if (!member) return failure(res, 'Member not found', [], 404); if (req.auth!.role === 'MEMBER' && member.userId !== req.auth!.sub) return failure(res, 'Insufficient permissions', [], 403); return success(res, member); }
export async function createMember(req: Request, res: Response) { const input = memberInput.parse(req.body); const passwordHash = await import('bcryptjs').then(({ hash }) => hash(input.password, 12)); const user = await prisma.user.create({ data: { name: input.name, phone: input.phone, email: input.email, passwordHash, role: 'MEMBER', member: { create: { fitnessGoal: input.fitnessGoal, heightCm: input.heightCm, weightKg: input.weightKg } } }, include: { member: true } }); return success(res, user, 201); }
export async function updateMember(req: Request, res: Response) { const { id } = idSchema.parse(req.params); const input = memberInput.partial().omit({ password: true }).parse(req.body); const member = await prisma.member.update({ where: { id }, data: { fitnessGoal: input.fitnessGoal, heightCm: input.heightCm, weightKg: input.weightKg, user: { update: { name: input.name, phone: input.phone, email: input.email } } }, include: { user: true } }); return success(res, member); }
export async function statusMember(req: Request, res: Response) { const { id } = idSchema.parse(req.params); const input = z.object({ active: z.boolean() }).parse(req.body); const member = await prisma.member.update({ where: { id }, data: { isActive: input.active, user: { update: { status: input.active ? 'ACTIVE' : 'INACTIVE' } } } }); return success(res, member); }
export async function deleteMember(req: Request, res: Response) { return statusMember({ ...req, body: { active: false } } as Request, res); }

export async function listServices(_req: Request, res: Response) { return success(res, await prisma.service.findMany({ where: { isActive: true }, include: { planServices: { include: { plan: true } } } })); }
export async function createService(req: Request, res: Response) { const input = z.object({ name: z.string().min(2), description: z.string().optional() }).parse(req.body); return success(res, await prisma.service.create({ data: input }), 201); }
export async function updateService(req: Request, res: Response) { const { id } = idSchema.parse(req.params); const input = z.object({ name: z.string().min(2).optional(), description: z.string().optional(), isActive: z.boolean().optional() }).parse(req.body); return success(res, await prisma.service.update({ where: { id }, data: input })); }
export async function deleteService(req: Request, res: Response) { const { id } = idSchema.parse(req.params); return success(res, await prisma.service.update({ where: { id }, data: { isActive: false } })); }

export async function listPlans(_req: Request, res: Response) { return success(res, await prisma.plan.findMany({ where: { isActive: true }, include: { services: { include: { service: true } } } })); }
export async function createPlan(req: Request, res: Response) { const input = z.object({ name: z.string().min(2), price: z.number().nonnegative(), durationMonths: z.number().int().positive().optional(), durationDays: z.number().int().positive().optional(), serviceIds: z.array(z.string()).default([]), discount: z.number().nonnegative().default(0), isPopular: z.boolean().default(false), isPremium: z.boolean().default(false) }).parse(req.body); return success(res, await prisma.plan.create({ data: { name: input.name, price: input.price, durationMonths: input.durationMonths, durationDays: input.durationDays, discount: input.discount, isPopular: input.isPopular, isPremium: input.isPremium, services: { create: input.serviceIds.map((serviceId) => ({ service: { connect: { id: serviceId } } })) } }, include: { services: true } }), 201); }
export async function updatePlan(req: Request, res: Response) { const { id } = idSchema.parse(req.params); const input = z.object({ name: z.string().optional(), price: z.number().nonnegative().optional(), isActive: z.boolean().optional(), isPopular: z.boolean().optional(), isPremium: z.boolean().optional() }).parse(req.body); return success(res, await prisma.plan.update({ where: { id }, data: input })); }
export async function deletePlan(req: Request, res: Response) { const { id } = idSchema.parse(req.params); return success(res, await prisma.plan.update({ where: { id }, data: { isActive: false } })); }

export const adminOnly = allowRoles('ADMIN');
