import { useQuery } from '@tanstack/react-query';
import { Text, View } from 'react-native';
import { RoleGate } from '../../components/RoleGate';
import { RoleNav, RoleScreen, StatusBadge, roleStyles as s } from '../../components/RoleScreen';
import { Card } from '../../components/ui';
import { colors } from '../../constants/theme';
import { memberRepository } from '../../services/memberRepository';
export default function AdminPayments() { return <RoleGate role="admin"><Payments /></RoleGate>; }
function Payments() { const { data } = useQuery({ queryKey: ['member', 'payments'], queryFn: memberRepository.getPayments }); return <RoleScreen title="Payments & Revenue" eyebrow="ADMIN · FINANCE"><Card style={{ backgroundColor: '#1C1408', borderColor: '#6F5A1E' }}><Text style={s.muted}>MONTHLY REVENUE</Text><Text style={{ color: colors.white, fontSize: 28, fontWeight: '800', marginTop: 6 }}>₹18,42,600</Text><Text style={{ color: colors.goldSoft, fontSize: 11, marginTop: 4 }}>↑ 9.2% vs last month</Text></Card><View style={{ flexDirection: 'row', flexWrap: 'wrap', gap: 10, marginTop: 12 }}>{[['DAILY AVG', '₹61,420'], ['PENDING', '₹1,28,900'], ['RENEWALS', '₹6,84,200'], ['REFUNDS', '₹18,400']].map(([label, value]) => <Card key={label} style={{ width: '47%' }}><Text style={s.muted}>{label}</Text><Text style={{ color: colors.white, fontSize: 17, fontWeight: '800', marginTop: 6 }}>{value}</Text></Card>)}</View><Text style={[s.heading, { marginTop: 20 }]}>Recent payments</Text>{data?.map((payment) => <Card key={payment.id} style={s.card}><View style={s.row}><View><Text style={{ color: colors.white, fontWeight: '700' }}>{payment.plan}</Text><Text style={s.muted}>{payment.date} · {payment.reference}</Text></View><View style={{ alignItems: 'flex-end' }}><Text style={{ color: colors.white, fontWeight: '800' }}>₹{payment.amount.toLocaleString('en-IN')}</Text><StatusBadge label={payment.status} /></View></View></Card>)}<RoleNav items={[{ label: 'Home', route: '/admin' }, { label: 'Members', route: '/admin/members' }, { label: 'Attendance', route: '/admin/attendance' }, { label: 'Payments', route: '/admin/payments' }, { label: 'More', route: '/admin/more' }]} /></RoleScreen>; }
