import { useQuery } from '@tanstack/react-query';
import { useLocalSearchParams } from 'expo-router';
import { Text, View } from 'react-native';
import { RoleGate } from '../../../components/RoleGate';
import { RoleScreen, StatusBadge, roleStyles as s } from '../../../components/RoleScreen';
import { Card, PrimaryButton } from '../../../components/ui';
import { colors } from '../../../constants/theme';
import { roleRepository } from '../../../services/roleRepository';
export default function AdminMemberProfile() { return <RoleGate role="admin"><Profile /></RoleGate>; }
function Profile() { const { id } = useLocalSearchParams<{ id: string }>(); const { data } = useQuery({ queryKey: ['admin', 'members'], queryFn: roleRepository.getAdminMembers }); const member = data?.find((item) => item.id === id) ?? data?.[0]; if (!member) return null; return <RoleScreen title="Member 360" eyebrow="ADMIN · MEMBER PROFILE"><View style={{ alignItems: 'center', marginBottom: 16 }}><View style={{ width: 70, height: 70, borderRadius: 35, backgroundColor: colors.surface2, alignItems: 'center', justifyContent: 'center' }}><Text style={{ color: colors.text2, fontSize: 24, fontWeight: '800' }}>{member.initials}</Text></View><Text style={{ color: colors.white, fontSize: 17, fontWeight: '800', marginTop: 8 }}>{member.name}</Text><Text style={s.muted}>{member.phone}</Text><StatusBadge label={member.status} /></View><Card><Text style={s.heading}>Membership</Text><Text style={s.muted}>{member.service} · {member.plan}</Text><Text style={s.muted}>Started · 12 Jul 2026</Text><Text style={s.muted}>Expires · {member.expiry} · {member.days} days</Text><PrimaryButton label="Renew / Extend" onPress={() => undefined} /></Card><Card><Text style={s.heading}>360 overview</Text>{['Subscription history', 'Payments', 'Attendance', 'Workout', 'Diet plan', 'PT sessions', 'Progress', 'Notifications', 'Activity timeline'].map((label) => <View key={label} style={[s.row, { borderBottomColor: colors.line, borderBottomWidth: 1, paddingVertical: 10 }]}><Text style={{ color: colors.text2, fontSize: 13 }}>{label}</Text><Text style={{ color: colors.redBright, fontSize: 18 }}>›</Text></View>)}</Card></RoleScreen>; }
