import express from 'express';
import cors from 'cors';
import helmet from 'helmet';
import pinoHttp from 'pino-http';
import { env } from './config/env';
import { authRouter } from './routes/auth';
import { coreRouter } from './routes/core';
import { businessRouter } from './routes/business';
import { resourceRouter } from './routes/resources';
import { reportsRouter } from './routes/reports';
import { errorHandler, notFound } from './middleware/errors';

export const app = express();
app.use(helmet());
app.use(cors({ origin: env.CORS_ORIGIN === '*' ? true : env.CORS_ORIGIN.split(',').map((item) => item.trim()) }));
app.use(express.json({ limit: '1mb' }));
app.use(pinoHttp());
app.get('/health', (_req, res) => res.json({ success: true, data: { service: 'gold-army-backend', status: 'healthy', timestamp: new Date().toISOString(), uptime: process.uptime() } }));
app.get('/api/health', (_req, res) => res.json({ success: true, data: { service: 'gold-army-backend', status: 'healthy', timestamp: new Date().toISOString(), uptime: process.uptime() } }));
app.use('/api/auth', authRouter);
app.use('/api', coreRouter);
app.use('/api', businessRouter);
app.use('/api', resourceRouter);
app.use('/api/reports', reportsRouter);
app.use(notFound);
app.use(errorHandler);
