import { router } from 'expo-router';
import { Pressable, SafeAreaView, ScrollView, StyleSheet, Text, View, type ViewStyle } from 'react-native';
import type { ReactNode } from 'react';
import { colors, spacing } from '../constants/theme';
import { useAuthStore } from '../store/auth';
import { BrandMark } from './BrandMark';

export function RoleScreen({ title, eyebrow, children, scroll = true }: { title: string; eyebrow: string; children: ReactNode; scroll?: boolean }) { const content = <View style={styles.inner}><View style={styles.header}><Pressable onPress={() => router.back()} style={styles.back}><Text style={styles.backText}>‹</Text></Pressable><View style={{ flex: 1 }}><Text style={styles.eyebrow}>{eyebrow}</Text><Text style={styles.title}>{title}</Text></View><BrandMark compact /></View>{children}</View>; return <SafeAreaView style={styles.safe}>{scroll ? <ScrollView contentContainerStyle={styles.content}>{content}</ScrollView> : content}</SafeAreaView>; }
export function RoleNav({ items }: { items: { label: string; route: string }[] }) { const signOut = useAuthStore((state) => state.signOut); return <View style={styles.nav}>{items.map((item) => <Pressable key={item.label} onPress={() => router.push(item.route as never)}><Text style={styles.navText}>{item.label}</Text></Pressable>)}<Pressable onPress={() => void signOut()}><Text style={[styles.navText, { color: colors.redBright }]}>Logout</Text></Pressable></View>; }
export function StatusBadge({ label }: { label: string }) { const tone = label === 'ACTIVE' || label === 'COMPLETED' ? colors.green : label === 'EXPIRED' || label === 'CANCELLED' ? colors.redBright : label === 'EXPIRING SOON' || label === 'PENDING' ? colors.amber : colors.goldSoft; return <View style={{ backgroundColor: `${tone}22`, borderRadius: 7, paddingHorizontal: 8, paddingVertical: 5 }}><Text style={{ color: tone, fontSize: 10, fontWeight: '800' }}>{label}</Text></View>; }
export const roleStyles = StyleSheet.create({ card: { marginBottom: 10 }, row: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', gap: 8 }, section: { marginTop: spacing.lg }, heading: { color: colors.white, fontSize: 15, fontWeight: '800', marginBottom: 10 }, muted: { color: colors.muted, fontSize: 12, lineHeight: 18 }, input: { backgroundColor: colors.surface2, borderColor: colors.line, borderWidth: 1, borderRadius: 10, color: colors.white, padding: 12, fontSize: 13 }, });
const styles = StyleSheet.create({ safe: { flex: 1, backgroundColor: colors.blackDeep }, content: { paddingBottom: 28 }, inner: { padding: spacing.xl, paddingTop: spacing.md }, header: { flexDirection: 'row', alignItems: 'center', gap: 10, marginBottom: spacing.lg }, back: { width: 38, height: 38, borderRadius: 10, backgroundColor: colors.surface, alignItems: 'center', justifyContent: 'center' }, backText: { color: colors.text2, fontSize: 28 }, eyebrow: { color: colors.goldSoft, fontSize: 10, fontWeight: '700', letterSpacing: 1 }, title: { color: colors.white, fontSize: 19, fontWeight: '800', marginTop: 2 }, nav: { borderTopColor: colors.line, borderTopWidth: 1, backgroundColor: colors.blackDeep, flexDirection: 'row', justifyContent: 'space-around', paddingHorizontal: 5, paddingVertical: 14 }, navText: { color: colors.muted, fontSize: 10, fontWeight: '700' } });
